### ISSUE TITLE
Remove NTNet

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/dev-cycles-initiative#3]
Code that creates NTNet interfaces, broadcasts signals, etc is very slow.

### Estimated Cost
- `/datum/component/ntnet_interface/Initialize` is 125.11ms.
- `/obj/proc/init_network_id` is 114.75ms over 1,076 calls.
    - Most of this is in `log_telecomms` (81.72ms) and is easily fixable. There is a path where it replaces the current network with a new one, which is ran regardless of if the networks are the same, which happens thousands of times in init. Check telecomms.log of any round!

### Solutions
NTNet and the general radio framework is an enormous piece of code that is completely invisible to players, as there is no interesting way to utilize NTNet itself. There exist things like the NTNet circuit components, but they are on their own isolated network and can be trivially replaced.

NTNet and the radio frequencies from atmos stuff can be completely removed. Aside from that, fixing the `log_telecomms` will lower a significant cost.

**Comment by Mothblocks** [comment]
For posterity: anything that "needs" NTNet should be changed to just work if comms is working fine. That's the only thing interesting about them.

**Comment by Mothblocks** [comment]
Okay basically all of this cost was in airlocks, so I'm going to mark this as solved for the purposes of the initiative.

**Comment by Stonetear** [comment]
I imagine the reasoning behind NTNet and packets was to create something similar to [Goonstation's packet system](https://wiki.ss13.co/Packets), where hacking is a sandbox mechanic such as knowing atmos or chemistry, rather than a outcomes mechanic, like xenobio or genetics where you push a button that says _hack._  

Perhaps the reason that it never caught on was that some maintainers disliked allowing players to [see](https://github.com/tgstation/tgstation/pull/60557#issuecomment-894755527) or [interact](https://discord.com/channels/326822144233439242/326831214667235328/870545460597764166) with NTnet at all.  I can more or less understand the reasoning, (although I disagree with it) but it still feels like a huge lost opportunity.

**Comment by Mothblocks** [comment]
I don't have access to your second link because I am not in Discord

What potential it has is irrelevant because the person who was working on it told us to expect a "part 2 soon" and then has been AWOL for 2 years. At the moment it is simply wasted cost. Any potential NTNet has should be melded into circuits.
